//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mac5SyncData.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mac5Entities : DbContext
    {
        public mac5Entities()
            : base("name=mac5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_MIH_ISERVICE_LINK> V_MIH_ISERVICE_LINK { get; set; }
        public virtual DbSet<V_MIL_ISERVICE_LINK> V_MIL_ISERVICE_LINK { get; set; }
    }
}
