//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mac5SyncData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MIL_ISERVICE_LINK
    {
        public short MILday { get; set; }
        public short MILmonth { get; set; }
        public short MILyear { get; set; }
        public string MILtype { get; set; }
        public string MILvnos { get; set; }
        public string MILcus { get; set; }
        public string MILstk { get; set; }
        public string MILjob { get; set; }
        public string MILdep { get; set; }
        public string MILper { get; set; }
        public string MILdoc { get; set; }
        public string MILmec { get; set; }
        public string MILsto { get; set; }
        public string MILstoMT { get; set; }
        public short MILlistNo { get; set; }
        public Nullable<double> MILquan { get; set; }
        public Nullable<double> MILquanP2 { get; set; }
        public Nullable<decimal> MILadisc { get; set; }
        public Nullable<decimal> MILcog { get; set; }
        public Nullable<float> MILconv { get; set; }
        public Nullable<decimal> MILdiscA { get; set; }
        public string MILdiscT { get; set; }
        public Nullable<decimal> MILvat { get; set; }
        public Nullable<decimal> MILsum { get; set; }
        public Nullable<short> MILcut { get; set; }
        public Nullable<short> MILstype { get; set; }
        public string MILuname { get; set; }
        public string MILdesc { get; set; }
        public string MILvCol1 { get; set; }
        public string MILvCol2 { get; set; }
        public string MILvCol3 { get; set; }
        public string MILvCol4 { get; set; }
        public string MILvCol5 { get; set; }
        public Nullable<short> MILcurC { get; set; }
        public Nullable<double> MILexchg { get; set; }
        public Nullable<decimal> MILacost { get; set; }
        public Nullable<short> MILpqm { get; set; }
        public Nullable<short> MILpmFrom { get; set; }
        public Nullable<short> MILpmTo { get; set; }
        public Nullable<short> MILtag { get; set; }
        public string MILlinkVCno { get; set; }
        public Nullable<System.DateTime> MILlinkVCdate { get; set; }
        public string MILlinkVCtype { get; set; }
        public string MILlinkVCdeposit { get; set; }
        public Nullable<short> MILlinkVCid { get; set; }
        public Nullable<short> MILclearUM { get; set; }
        public Nullable<System.DateTime> MILexpDATE { get; set; }
        public string MILnotes { get; set; }
        public Nullable<short> MILnotKL { get; set; }
        public Nullable<System.DateTime> MILdelvDT { get; set; }
        public Nullable<System.DateTime> MILdateSP { get; set; }
        public Nullable<decimal> MILnumCSP { get; set; }
        public Nullable<short> MILnumISP { get; set; }
        public Nullable<decimal> MILcost { get; set; }
        public Nullable<decimal> MILucost { get; set; }
        public Nullable<decimal> MILuprice { get; set; }
        public Nullable<short> MILuseQuanP { get; set; }
        public Nullable<byte> MILfitem { get; set; }
    }
}
