//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mac5SyncData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MIH_ISERVICE_LINK
    {
        public Nullable<System.DateTime> MIHdate { get; set; }
        public string MIHtype { get; set; }
        public string MIHvnos { get; set; }
        public string MIHjob { get; set; }
        public string MIHcus { get; set; }
        public string DEBnameT { get; set; }
        public Nullable<decimal> MIHcog { get; set; }
        public string MIHnotes { get; set; }
    }
}
